export const products = [
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Mobile Phone",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
    {
      title: "Motorola Edge 30 Pro",
      actualPrice: "500",
      salePrice: "200",
      image: "https://cdn1.smartprix.com/rx-iy2wIvPwa-w1200-h1200/y2wIvPwa.jpg",
      brand: "Flipkart",
      category : "Mobile",
      src: "https://www.smartprix.com/mobiles",
    },
  ];